theme: jekyll-theme-minimal
title: <p style="color:red;">ERDI MYFTARAGA</p>
description: >
    My description
    <br><br>
    <a href="https://www.linkedin.com/in/erdi-myftaraga/">website</a>
layout: page
