theme: jekyll-theme-minimal
title: <p style="color:red; font-size:50%">ERDI MYFTARAGA</p>
description: >
    My description
    <br><br>
    <a href="https://www.linkedin.com/in/erdi-myftaraga/">website</a>
layout: page
