theme: jekyll-theme-minimal
title: <p style="color:#2F2F2F; font-size:75%">ERDI MYFTARAGA</p>
description: >
    My description
    <br><br>
    <a href="https://www.linkedin.com/in/erdi-myftaraga/">website</a>
layout: page
