title: <p style="color:#2F2F2F;font-family:monospace;font-size:16px;font-weight:900;padding: 0 0px;">ERDI MYFTARAGA</p>
description: >
    <p style="font-weight:normal;color:#2F2F2F">Geotechnical engineer at Green Geotechnics, based in Tirana and working in marine geotechnics projects.
    TV series, walking, dataviz, history, football, and pasta, in reverse order.</p>
theme: jekyll-theme-minimal
github:
    is\_project\_page:false
