theme: jekyll-theme-minimal
title: <p style="color: #2F2F2F; font-size: 16px; font-weight: 900;">ERDI MYFTARAGA</p>
description: >
    Geotechnical engineer at Green Geotechnics, based in Tirana and working in marine geotechnics projects.
    <br>
    <a href="your_website">website</a>
layout: page
