theme: jekyll-theme-minimal
title: Erdi's blog
description: >
    My description
    <br><br>
    <a href="your_website">website</a>
layout: page
owner:
  name: Ted Laderas
  bio: "This is a sample Jekyll academic website."
  email: laderast@ohsu.edu
  twitter: laderast
  linkedin: #username
  github: laderast
