title: <p style="color:#2F2F2F; font-size:16px; font-weight:900;">ERDI MYFTARAGA</p>
logo: https://media-exp1.licdn.com/dms/image/C5603AQHXrY0nQvjm6A/profile-displayphoto-shrink_200_200/0/1642621943536?e=1658361600&v=beta&t=BEKf4QEcSWXeSudU7UWKv3bFCYL-HSdEDQtxE6JWnKc
description: >
    <p style="color:#2F2F2F">Geotechnical engineer at Green Geotechnics, based in Tirana and working in marine geotechnics projects.
    TV series, walking, dataviz, history, football, and pasta, in reverse order.</p>
theme: jekyll-theme-minimal
