title:
description: >
    <p style="font-weight:normal;color:#2F2F2F">Geotechnical engineer at Green Geotechnics, based in Tirana and working in marine geotechnics projects. 
    I hope the content of these short/long blog posts can be useful to someone. Posts mostly include application of data science, machine learning and 
    data visualization concepts in geotechnical engineering, with focus on geotechnical site assessment. Other topics can also show up. 
    Sometimes the code is included along the main text and sometimes it isn't. The work has been almost exclusively done with 
    <a href="https://www.r-project.org/" title="R WEBPAGE" target="_blank">R</a> code.
    <hr>
    <sec>NOTE</sec>
    These articles represent my opinion on the material they cover and not the views of my employer, obviously. 
    The content comes with absolutely no warranty. Use at your own risk.
    <hr>
    The work licensed under a Creative Commons Attribution-NonCommercial 4.0 International License 
    <a href="https://creativecommons.org/licenses/by-nc/4.0/" title="creativecommons.org" target="_blank">CC BY-NC 4.0</a>.
    </p>
theme: jekyll-theme-minimal
github:
    is\_project\_page:false
